#pragma once

#include <map>

namespace vp::utility
{
    enum class country_code
    {
        // players' countries in hltv top 30 world ranking
        international,
        argentina,
        australia,
        brazil,
        china,
        czech_republic,
        denmark,
        finland,
        france,
        germany,
        mongolia,
        poland,
        portugal,
        russia,
        sweden,
        turkey,
        ukraine,
        united_kingdom,
        united_states,
        belgium,
        bosnia,
        bulgaria,
        canada,
        chile,
        estonia,
        hungary,
        israel,
        kazakhstan,
        kosovo,
        latvia,
        mexico,
        montenegro,
        netherlands,
        new_zealand,
        norway,
        romania,
        serbia,
        slovakia,
        south_africa,
        spain,
        switzerland,
        uruguay
    };

    static const inline std::map<country_code, double> PLAYERS_DISTRIBUTION{
        {country_code::argentina, 0.0322},
        {country_code::australia, 0.0456},
        {country_code::brazil, 0.0972},
        {country_code::china, 0.0231},
        {country_code::czech_republic, 0.0186},
        {country_code::denmark, 0.0722},
        {country_code::finland, 0.0309},
        {country_code::france, 0.0258},
        {country_code::germany, 0.0267},
        {country_code::mongolia, 0.0263},
        {country_code::poland, 0.0644},
        {country_code::portugal, 0.0276},
        {country_code::russia, 0.0733},
        {country_code::sweden, 0.0423},
        {country_code::turkey, 0.0204},
        {country_code::ukraine, 0.0332},
        {country_code::united_kingdom, 0.0267},
        {country_code::united_states, 0.0782},
        {country_code::belgium, 0.0093},
        {country_code::bosnia, 0.0093},
        {country_code::bulgaria, 0.0111},
        {country_code::canada, 0.0166},
        {country_code::chile, 0.0093},
        {country_code::estonia, 0.0093},
        {country_code::hungary, 0.0093},
        {country_code::israel, 0.0093},
        {country_code::kazakhstan, 0.0137},
        {country_code::kosovo, 0.0101},
        {country_code::latvia, 0.0093},
        {country_code::mexico, 0.0093},
        {country_code::montenegro, 0.0093},
        {country_code::netherlands, 0.0093},
        {country_code::new_zealand, 0.0147},
        {country_code::norway, 0.0093},
        {country_code::romania, 0.0111},
        {country_code::serbia, 0.0101},
        {country_code::slovakia, 0.0111},
        {country_code::south_africa, 0.0128},
        {country_code::spain, 0.0137},
        {country_code::switzerland, 0.0093},
        {country_code::uruguay, 0.0093}};
} // namespace vp::utility