#pragma once

#include <map>

namespace vp::utility
{
    enum class country_code
    {
        // players' countries in hltv top 30 world ranking
        International,
        Argentina,
        Australia,
        Brazil,
        China,
        Czech_Republic,
        Denmark,
        Finland,
        France,
        Germany,
        Mongolia,
        Poland,
        Portugal,
        Russia,
        Sweden,
        Turkey,
        Ukraine,
        United_Kingdom,
        United_States,
        Belgium,
        Bosnia,
        Bulgaria,
        Canada,
        Chile,
        Estonia,
        Hungary,
        Israel,
        Kazakhstan,
        Kosovo,
        Latvia,
        Mexico,
        Montenegro,
        Netherlands,
        New_Zealand,
        Norway,
        Romania,
        Serbia,
        Slovakia,
        South_Africa,
        Spain,
        Switzerland,
        Uruguay
    };

    enum class region_code
    {
        Western_Europe,
        Eastern_Europe,
        CIS,
        Americas,
        Asia,
        Oceania
    };

    static const inline std::map<country_code, double> players_distribution{
        {country_code::Argentina, 0.0322},
        {country_code::Australia, 0.0456},
        {country_code::Brazil, 0.0972},
        {country_code::China, 0.0231},
        {country_code::Czech_Republic, 0.0186},
        {country_code::Denmark, 0.0722},
        {country_code::Finland, 0.0309},
        {country_code::France, 0.0258},
        {country_code::Germany, 0.0267},
        {country_code::Mongolia, 0.0263},
        {country_code::Poland, 0.0644},
        {country_code::Portugal, 0.0276},
        {country_code::Russia, 0.0733},
        {country_code::Sweden, 0.0423},
        {country_code::Turkey, 0.0204},
        {country_code::Ukraine, 0.0332},
        {country_code::United_Kingdom, 0.0267},
        {country_code::United_States, 0.0782},
        {country_code::Belgium, 0.0093},
        {country_code::Bosnia, 0.0093},
        {country_code::Bulgaria, 0.0111},
        {country_code::Canada, 0.0166},
        {country_code::Chile, 0.0093},
        {country_code::Estonia, 0.0093},
        {country_code::Hungary, 0.0093},
        {country_code::Israel, 0.0093},
        {country_code::Kazakhstan, 0.0137},
        {country_code::Kosovo, 0.0101},
        {country_code::Latvia, 0.0093},
        {country_code::Mexico, 0.0093},
        {country_code::Montenegro, 0.0093},
        {country_code::Netherlands, 0.0093},
        {country_code::New_Zealand, 0.0147},
        {country_code::Norway, 0.0093},
        {country_code::Romania, 0.0111},
        {country_code::Serbia, 0.0101},
        {country_code::Slovakia, 0.0111},
        {country_code::South_Africa, 0.0128},
        {country_code::Spain, 0.0137},
        {country_code::Switzerland, 0.0093},
        {country_code::Uruguay, 0.0093}};
} // namespace vp::utility