#pragma once

#include "countryenum.hpp"
#include "magic_enum.hpp"

#include <vector>

namespace vp::utility
{
    struct country_and_skill_limit
    {
        const double c_distribuition_tier;
        const std::uint8_t c_begin_range;
        const std::uint8_t c_end_range;
        std::vector<country_code> _countries_to_choose;
    };

    static std::vector<country_and_skill_limit>
        s_players_generator_configs{
            {0.00184,
             94,
             98,
             {country_code::sweden, country_code::sweden, country_code::france,
              country_code::france, country_code::ukraine,
              country_code::ukraine, country_code::brazil, country_code::brazil,
              country_code::denmark, country_code::bosnia,
              country_code::slovakia}},
            {0.00278,
             91,
             95,
             {country_code::russia, country_code::russia, country_code::russia,
              country_code::denmark, country_code::denmark,
              country_code::denmark, country_code::bosnia, country_code::bosnia,
              country_code::poland, country_code::poland, country_code::sweden,
              country_code::france, country_code::ukraine, country_code::brazil,
              country_code::norway, country_code::united_states}},
            {0.00463,
             88,
             92,
             {country_code::sweden,        country_code::sweden,
              country_code::sweden,        country_code::france,
              country_code::france,        country_code::france,
              country_code::denmark,       country_code::denmark,
              country_code::russia,        country_code::russia,
              country_code::ukraine,       country_code::brazil,
              country_code::united_states, country_code::slovakia,
              country_code::canada,        country_code::latvia,
              country_code::estonia,       country_code::kazakhstan,
              country_code::belgium,       country_code::germany}},
            {0.00927,
             84,
             89,
             {country_code::denmark,        country_code::denmark,
              country_code::denmark,        country_code::sweden,
              country_code::sweden,         country_code::sweden,
              country_code::france,         country_code::france,
              country_code::brazil,         country_code::brazil,
              country_code::bosnia,         country_code::bosnia,
              country_code::united_states,  country_code::united_states,
              country_code::russia,         country_code::ukraine,
              country_code::poland,         country_code::slovakia,
              country_code::canada,         country_code::latvia,
              country_code::estonia,        country_code::norway,
              country_code::kazakhstan,     country_code::finland,
              country_code::israel,         country_code::australia,
              country_code::czech_republic, country_code::turkey,
              country_code::bulgaria}},
            {0.02778,
             81,
             86,
             {country_code::denmark,       country_code::sweden,
              country_code::france,        country_code::russia,
              country_code::ukraine,       country_code::brazil,
              country_code::bosnia,        country_code::poland,
              country_code::united_states, country_code::slovakia,
              country_code::canada,        country_code::latvia,
              country_code::estonia,       country_code::norway,
              country_code::kazakhstan,    country_code::israel,
              country_code::australia,     country_code::czech_republic,
              country_code::germany,       country_code::united_kingdom,
              country_code::hungary,       country_code::netherlands,
              country_code::serbia}},
            {0.09261,
             77,
             83,
             {country_code::argentina,     country_code::australia,
              country_code::brazil,        country_code::czech_republic,
              country_code::denmark,       country_code::finland,
              country_code::france,        country_code::germany,
              country_code::mongolia,      country_code::poland,
              country_code::portugal,      country_code::russia,
              country_code::sweden,        country_code::turkey,
              country_code::ukraine,       country_code::united_kingdom,
              country_code::united_states, country_code::belgium,
              country_code::bosnia,        country_code::bulgaria,
              country_code::canada,        country_code::chile,
              country_code::estonia,       country_code::hungary,
              country_code::israel,        country_code::kazakhstan,
              country_code::kosovo,        country_code::latvia,
              country_code::montenegro,    country_code::netherlands,
              country_code::norway,        country_code::romania,
              country_code::serbia,        country_code::slovakia,
              country_code::south_africa,  country_code::spain,
              country_code::switzerland,   country_code::uruguay}},
            {0.46295,
             69,
             79,
             {magic_enum::enum_values<country_code>().cbegin(),
              magic_enum::enum_values<country_code>().cend()}},
            {0.23148,
             64,
             72,
             {magic_enum::enum_values<country_code>().cbegin(),
              magic_enum::enum_values<country_code>().cend()}},
            {1,
             55,
             67,
             {magic_enum::enum_values<country_code>().cbegin(),
              magic_enum::enum_values<country_code>().cend()}}};

    static std::vector<country_and_skill_limit>
        s_coaches_generator_configs{
            {0.047,
             81,
             98,
             {country_code::australia,      country_code::brazil,
              country_code::czech_republic, country_code::denmark,
              country_code::finland,        country_code::france,
              country_code::germany,        country_code::poland,
              country_code::russia,         country_code::sweden,
              country_code::turkey,         country_code::ukraine,
              country_code::united_kingdom, country_code::united_states,
              country_code::belgium,        country_code::bosnia,
              country_code::bulgaria,       country_code::canada,
              country_code::estonia,        country_code::hungary,
              country_code::israel,         country_code::kazakhstan,
              country_code::latvia,         country_code::netherlands,
              country_code::norway,         country_code::serbia,
              country_code::slovakia}},
            {0.094,
             77,
             83,
             {country_code::argentina,     country_code::australia,
              country_code::brazil,        country_code::czech_republic,
              country_code::denmark,       country_code::finland,
              country_code::france,        country_code::germany,
              country_code::mongolia,      country_code::poland,
              country_code::portugal,      country_code::russia,
              country_code::sweden,        country_code::turkey,
              country_code::ukraine,       country_code::united_kingdom,
              country_code::united_states, country_code::belgium,
              country_code::bosnia,        country_code::bulgaria,
              country_code::canada,        country_code::chile,
              country_code::estonia,       country_code::hungary,
              country_code::israel,        country_code::kazakhstan,
              country_code::kosovo,        country_code::latvia,
              country_code::montenegro,    country_code::netherlands,
              country_code::norway,        country_code::romania,
              country_code::serbia,        country_code::slovakia,
              country_code::south_africa,  country_code::spain,
              country_code::switzerland,   country_code::uruguay}},
            {0.464,
             69,
             79,
             {magic_enum::enum_values<country_code>().cbegin(),
              magic_enum::enum_values<country_code>().cend()}},
            {0.232,
             64,
             72,
             {magic_enum::enum_values<country_code>().cbegin(),
              magic_enum::enum_values<country_code>().cend()}},
            {1,
             55,
             67,
             {magic_enum::enum_values<country_code>().cbegin(),
              magic_enum::enum_values<country_code>().cend()}}};
} // namespace vp::utility